🚧 Update to SDK 26.2.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👷🏼‍♂️🈚️❗️👃🏼

Full error log:
Error:  Cannot acces entryPath
File C:\Users\me\work\collboard\frames\src\moduleSampleBasic.tsx not found

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\frames\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:52:27)
at Generator.next (<anonymous>)
at fulfilled (C:\Users\me\work\collboard\frames\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:5:58)